snowflake_user = "ChaiRavi"
snowflake_password = "Halonix@27"
snowflake_account = "qaofcdp-edb17240"
snowflake_warehouse = "Compute_WH"
snowflake_database = "TESTDB"
snowflake_schema = "MYSCHEMA" 
snowflake_role = "ACCOUNTADMIN"
